" vim: set foldmethod=marker foldmarker={,} foldlevel=0 :
" Environment {
    " Basics {
        set nocompatible        " 不兼容模式
        filetype off            " required
    " }

    "-- 跨平台支持 --"
    " Identify platform {
        silent function! OSX()
            return has('macunix')
        endfunction
        silent function! LINUX()
            return has('unix') && !has('macunix') && !has('win32unix')
        endfunction
        silent function! WINDOWS()
            return  (has('win32') || has('win64'))
        endfunction
    " }
    " Windows Compatible {
        if WINDOWS()
          set runtimepath=$HOME/.vim,$VIM/vimfiles,$VIMRUNTIME,$VIM/vimfiles/after,$HOME/.vim/after
        endif
    " }
" }

"-- 全局配置 --"
" global options {
    "let g:my_leader=','
    "let g:my_localleader='\'
    let g:bundle_groups=['general', 'deoplete', 'ui']
    "let g:bundle_groups=['general', 'neocomplete', 'ui']
" }

" mapleader {
    if exists('g:my_leader')
        let mapleader=g:my_leader
    else
        let mapleader="\<Space>"
    endif
" }

"-- 加载配置文件 --"
" source configurations {
    source ~/.vim/vimrcs/1.plugins.vim
    source ~/.vim/vimrcs/2.general.vim
    source ~/.vim/vimrcs/3.ui.vim
    source ~/.vim/vimrcs/4.keymappings.vim
" }
